### ISSUE TITLE
how do i log into gelbooru?

### ISSUE THREAD

**Issue by degensmit** [Chirmaya/BooruSlideshow#101]
in order to use gelbooru inside of booru slideshow, it says i need to log in. how do i do this? (sry if dumb questions lol)

**Comment by Znunu** [comment]
You mean that it's stuck on "Searching for images...". That has nothing to do with being logged in. Booru slideshow hasn't been updated in a long while and recent changes from gelbooru have finally broken it.

**Comment by Chirmaya** [comment]
The updated code is no longer being released.

**Comment by JohnWLuo** [comment]
I made a new pull request that fixes the gelbooru problem
