### ISSUE TITLE
search on Gelbooru not working 

### ISSUE THREAD

**Issue by hattorySG** [Chirmaya/BooruSlideshow#104]
![image](https://user-images.githubusercontent.com/97853695/149677755-6b5a0d81-eede-4b51-96f0-f603d9e7d108.png)
Infinite searching

**Comment by hennessy100k** [comment]
https://twitter.com/gelbooru/status/1477788287599325184
Gelbooru updated their API

**Comment by Chirmaya** [comment]
This is now fixed.
