### ISSUE TITLE
image not found when search loli

### ISSUE THREAD

**Issue by Mikusho** [Chirmaya/BooruSlideshow#114]
![image](https://user-images.githubusercontent.com/50960187/177383885-1d34f53f-650b-45c0-adc7-e5b6c841887d.png)
taking 4ever when search loli images :v

**Comment by Mikusho** [comment]
i did that but just same...

**Comment by Chirmaya** [comment]
Can you confirm you are using version 10?
And can you hit F12 and see if there are repeated messages in the console log?

**Comment by Mikusho** [comment]
![image](https://user-images.githubusercontent.com/50960187/177386914-a5c88358-9658-4244-8de7-21d48df7d60c.png)
also gelbooru don't work with any search query..
firefox 102.0 64bit
but work fine in chrome

**Comment by Mikusho** [comment]
ah shit yeah i m using ver 8.0 XD

**Comment by Chirmaya** [comment]
The Firefox version will be updated once they support Manifest v3.
