### ISSUE TITLE
Suggestion:  Newer port for FF

### ISSUE THREAD

**Issue by Ruggitt** [Chirmaya/BooruSlideshow#119]
Not sure the lengths you need to go to for porting chromium add-ons to Firefox but I'd really appreciate it if someone could give it a touch up with a newer version (currently on 7.19/8.0 while chrome is 10.1).

I've been running Chrome BS for a few years now, despite not actually using the browser as a daily driver.  Ive been checking in on FF's port to see if its ever gotten updated but sadly not.  Just feels wrong giving google info on my more private preferences.

**Comment by Chirmaya** [comment]
It will be ported once Firefox supports Manifest v3.

**Comment by Ruggitt** [comment]
alright, awesome.  Can't wait and thanks for all the work you've done.
