### ISSUE TITLE
Danbooru images return 403

### ISSUE THREAD

**Issue by SmilyPie1989** [Chirmaya/BooruSlideshow#134]
Some recent changes seem to have been made to how Danbooru handles bot and app traffic that causes images to return 403.

See: https://danbooru.donmai.us/forum_topics/25845?page=2#forum_post_263939

**Comment by clst** [comment]
can be fixed by either adding a referer to cdn.donmai.us images or including cdn.donmai.us in the MFv3 hosts so it gets all the cookies.

**Comment by SmilyPie1989** [comment]
For anyone like me who implemented the solution properly and Danbooru still didn't return 200 OK, you have to actually remove the extension from Chrome and then reinstall it after making the changes. Changes to the .js files appeared to work without reinstallation (as evidenced by me breaking it one time), but I guess manifest changes don't go through until reinstallation.

To fix the issue, I modified the "requestHeaders" block in "rules_header_referer.json". I changed "header" to "Referer" and "value" to "DanbooruUser######" with the #'s being my user ID. I also added "https://cdn.donmai.us/*" to the "host_permissions" in "manifest.json".

It's possible only one of the two file modifications are necessary to fix this, but it works for me as is.
