### ISSUE TITLE
Button to Toggle Auto-Fit?

### ISSUE THREAD

**Issue by MC-the-Fool** [Chirmaya/BooruSlideshow#15]
I was wondering if you could make a button on the keyboard to Toggle Auto-Fit?

Also thank you for making this extension.  I use it all the time!

**Comment by Chirmaya** [comment]
Thanks for the suggestion and comment! I'll add this soon!

**Comment by Chirmaya** [comment]
This is now in v7.7 that has just been pushed to the Chrome webstore. (Should be available within an hour.)
