### ISSUE TITLE
Trouble with Derpibooru

### ISSUE THREAD

**Issue by MC-the-Fool** [Chirmaya/BooruSlideshow#25]
I haven't been able to search Multiple Word tags on Derpibooru since the update.  Putting the word as "Twilight Sparkle" or "Twilight_Sparkle" will both yield no results. I also am not able to use the "-"tag to exclude things on Derpibooru anymore. All other websites seem to be working fine.

**Comment by Chirmaya** [comment]
Thanks for catching this! This is now fixed in v7.13. (Just tried with "twilight_sparkle -safe")
