### ISSUE TITLE
Front Page Misspelling on keyboard shortcuts listing

### ISSUE THREAD

**Issue by densedever** [Chirmaya/BooruSlideshow#31]
On the Firefox extension, the listing for the keyboard shortcuts at the bottom of the front page has a typo:

```
Previous (← or A)
Next (→ or A) <- here
Back 10 (W)
Forward 10 (S)
```

Next should be S instead of the duplicated A.

**Comment by Chirmaya** [comment]
Thanks for catching this! This will be fixed in v7.14.
