### ISSUE TITLE
Derpibooru not displaying all images

### ISSUE THREAD

**Issue by Grandpa-Bard** [Chirmaya/BooruSlideshow#36]
For some reason, when searching for images, booru slideshow does not show all images, when searching for something like (pinkie_pie dancing animated) booru slideshow only shows me 20 or so results, while the website shows me hundreds.

**Comment by fwerd85** [comment]
This seems to be happening to me only on the firefox version, and it seems like it's only displaying the first image per page of results. Could you check to see if it's doing the same for you?
