### ISSUE TITLE
Ability to add other imageboards

### ISSUE THREAD

**Issue by Immediate-Zero** [Chirmaya/BooruSlideshow#37]
I was wondering if you could add the ability for people to add their own boorus. There is a app for Android/Apple that can allow you to search your choice of booru called Anime Boxes.  It can be found at www.animebox.es. If you'd like to see for yourself.  Not sure if it could give you an idea for how to do it, or if you could reverse engineer it.  But if possible I'd really love to be able to have such a thing available via this extention.

Regardless, Thanks for this app and for all your hard work!

**Comment by jpfingstmann** [comment]
Alternatively, I was poking around the github code and replaced an existing booru item with one of my choosing, but I'm not entirely certain how I would go about turning this back into a Firefox plugin, when I run the slideshow.html file directly, it doesn't run.

**Comment by jpfingstmann** [comment]
Actually, about:debugging  lets you load the temporary addon, you just have to specify the manifest.js from the package.  You can probably poke around the code to add another imageboard yourself, if you wanted to.  I just did a search/replace of all instances of danbooru.donmai.us with my danbooru based imageboard of choice and it seems to work.
