### ISSUE TITLE
History

### ISSUE THREAD

**Issue by densm** [Chirmaya/BooruSlideshow#38]
Would be nice to have an option to be able to have some search history. Form recovery extensions don't work with BooruSlideshow and sometimes restoring session with Chrome or The Great Suspender gives tabs with blank search field. Or I fail to press ctrl-c before reloading and ctrl-v gives nothing. Ofc logging should be just an option it should be clear if it is on every time user uses BooruSlideshow

**Comment by Chirmaya** [comment]
Thanks a ton for the suggestion! I've just added this to v7.18, which should be available shortly.
