### ISSUE TITLE
Can't unmute webms

### ISSUE THREAD

**Issue by Kennyloggin** [Chirmaya/BooruSlideshow#48]
Having an issue with the latest version of chrome where i am unable to unmute webms which have sound.

**Comment by agitatedturk** [comment]
Seconded

**Comment by Bl4Cc4t** [comment]
thirded

**Comment by AweOnMachina** [comment]
You can fix this with a quick google. It was a "feature" with the new chrome update, not sure Chirmaya can do much about it.
