### ISSUE TITLE
Suggestion: the ability to blacklist a certain combination of tags like+this

### ISSUE THREAD

**Issue by Pan-exe** [Chirmaya/BooruSlideshow#69]

**Comment by khetarK** [comment]
Hello, I have an issue with Blacklist when using Gelbooru! For example, when I blacklist the tag (Fat_man) it will blacklist it and show no result of the tag but when I tried to test the blacklist feature on a big tag like (Dark_skinned_man) it did not work! What should I do to blacklist big tags?
