### ISSUE TITLE
Suggestion: custom boorus

### ISSUE THREAD

**Issue by ghost** [Chirmaya/BooruSlideshow#75]
Allow us to choose a booru backend and provide a link to the site, and then let us search from there. Many booru apps on mobile devices have this feature and it works great for "booru.org" sites.

**Comment by PupBrutus** [comment]
+1 especially if you could choose connect it with http://hydrusnetwork.github.io/ by allowing both URL and port

**Comment by SelwynCoy** [comment]
+1, I've seen this feature on similar mobile apps as well. Being able to add custom boorus would add a lot of helpful flexibility to the addon.
