### ISSUE TITLE
atfbooru has moved

### ISSUE THREAD

**Issue by littlesub1106** [Chirmaya/BooruSlideshow#77]
After legal issues ensued ATF has moved to https://booru.allthefallen.moe/ please update it in Booru Slideshow when you get a moment. Thank you again for the continued support.

**Comment by hpcjosh** [comment]
Creator is no longer working on it, you can download the source files and update the url in notepad++ in the atfbooru.js file in the site managers folder

**Comment by jylescoad-ward** [comment]
fixed in my fork
