### ISSUE TITLE
Suggestion: idol.sankakucomplex.com

### ISSUE THREAD

**Issue by Theonlyblade** [Chirmaya/BooruSlideshow#82]
idol.sankakucomplex.com Is there areason we cant get this site?

seems like a better version of realbooru.

**Comment by DontTalkToMeThx** [comment]
https://github.com/Chirmaya/BooruSlideshow/issues/76

**Comment by Theonlyblade** [comment]
https://twitter.com/Chirmaya/status/1238334477056856064

**Comment by DontTalkToMeThx** [comment]
Yeah, I was the one working on it. I also replied to that tweet :P

**Comment by Theonlyblade** [comment]
So, maintenance mode?
