### ISSUE TITLE
Sort results by date?

### ISSUE THREAD

**Issue by deeezeeeem** [Chirmaya/BooruSlideshow#83]
In version 8.0 my results were sorted by date, but now I'm getting an issue where older posts are being shown before newer ones. I think it's pulling posts from the topmost site selected initially, and then moving down.

**Comment by Chirmaya** [comment]
I'll be fixing that and the preloading in a little bit. Thanks!

**Comment by deeezeeeem** [comment]
I appreciate it thanks.

**Comment by Chirmaya** [comment]
I've fixed the two issues in 9.1 which is now available.
