### ISSUE TITLE
rule34.xxx is marked as down; Firefox Version

### ISSUE THREAD

**Issue by AccountNameIsTaken** [Chirmaya/BooruSlideshow#98]
rule34.xxx is marked as down, even though it's not, in the Firefox version. Did the API Key change?

**Comment by icarlyismybible** [comment]
Same happening in chrome as well

**Comment by DracoTomes** [comment]
Using the Chrome Plugin (in Opera) I get the following error:

Access to XMLHttpRequest at 'https://api.rule34.xxx//index.php?page=dapi&s=post&q=index&limit=1' (redirected from 'https://rule34.xxx/index.php?page=dapi&s=post&q=index&limit=1') from origin 'chrome-extension://lohkpdhklanigahgacmihfdlcfbbblgj' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by DracoTomes** [comment]
OK I found a fix - since rule34.xxx redirects requests to api.rule34.xxx you need to allow the extension access to that site.
You need to edit the manifest,json file in the unpacked zip and in line 38 cahnge https://rule34.xx to either https://api.rule34.xxx or you can do https://*.rule34.xxx like it's done with gelbooru already.

**Comment by AccountNameIsTaken** [comment]
> 
> 
> OK I found a fix - since rule34.xxx redirects requests to api.rule34.xxx you need to allow the extension access to that site.
> 
> You need to edit the manifest,json file in the unpacked zip and in line 38 change https://rule34.xx to either https://api.rule34.xxx or you can do https://*.rule34.xxx like it's done with gelbooru already.
> 
> Then you need to re-add the extension.
> 
> Your blacklist, if you use it should be saved, but I would advice saving and re-adding it need be.

Excellent insight! Thank you! I've made a PR to support this change, so that others can at least see the fix. I don't know if anyone is looking at this repo anymore, as it says on the main page.
Thanks DracoTomes!
